#pragma once

#define INIT_SCREEN_WIDTH 900
#define INIT_SCREEN_HEIGHT 600
#define CELL_SIZE 15
#define LINE_WIDTH 1
#define LINE_COLOR 0x1f1f1f1f
#define ROWS INIT_SCREEN_HEIGHT/CELL_SIZE
#define COLUMNS INIT_SCREEN_WIDTH/CELL_SIZE


