#pragma once

#define INIT_SCREEN_WIDTH 1500
#define INIT_SCREEN_HEIGHT 900
#define CELL_SIZE 10
#define ROWS INIT_SCREEN_HEIGHT/CELL_SIZE
#define COLUMNS INIT_SCREEN_WIDTH/CELL_SIZE
#define LINE_WIDTH 1
#define LINE_COLOR 0x1f1f1f1f


